[metadata]
keywords = ["electronics", "keyboards"]
description = "Split Keyboard Gallery - tool for browsing over 100 keyboards and filtering them by properties"
author = "nietaki"
image = "images/screenshot.png"
