baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Split Keyboard Gallery'

theme = "piccolo"

[outputs]
home = ["HTML"]

[module]
[[module.mounts]]
source = 'assets'
target = 'assets'

  [[module.imports]]
    path = 'github.com/gethugothemes/hugo-modules/seo-tools/basic-seo'

[menus]
  [[menus.main]]
    name = 'Table View'
    pageRef = '/index.html'
    weight = 10

  [[menus.main]]
    name = 'Gallery'
    pageRef = '/gallery/'
    weight = 15

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20

  [[menus.right]]
    name = 'Layout Comparison Tool'
    URL = 'https://jhelvy.shinyapps.io/splitkbcompare/'
    weight = 10

  [[menus.right]]
    name = 'GitHub'
    URL = 'https://github.com/NTK-studio/split-keyboard-gallery'
    weight = 20

