baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Split Keyboard Gallery'

theme = "piccolo"

[outputs]
home = ["HTML"]

[module]
[[module.mounts]]
source = 'assets'
target = 'assets'

[menus]
  [[menus.main]]
    name = 'Table View'
    pageRef = '/'
    weight = 10

  [[menus.right]]
    name = 'GitHub'
    URL = 'https://github.com/NTK-studio/split-keyboard-gallery'
    weight = 20
